/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "efpewqrpnhfgyagtujmg";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmcGV3cXJwbmhmZ3lhZ3R1am1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NTAxNDMsImV4cCI6MjA3OTUyNjE0M30.maii3hGMV-VUQfkQS4tr0Ss0Icsg7InPgAuXQX5ikm8";
